### ISSUE TITLE
text2command Seite ist leer

### ISSUE THREAD

**Issue by Waldi544** [ioBroker/ioBroker.text2command#69]
ch habe vor einigen Tagen den text2command Adapter installiert mit Telegram verbunden und einige Befehle erstellt.
Hat gut funktioniert. Wenn ich jetzt wieder auf den "Kommandos.0" Button drücke öffnet sich die Seite aber sie ist völlig leer. Ich kann weder auf die alten Befehle zugreifen noch neue dazuschreiben. Die bestehenden Befehle werden aber über Telegam problemlos ausgeführt. Auch über Instanzen - "Adapter Webseite öffnen" nur eine leere Seite. Der Adapter wird grün angezeigt. Was kann ich machen um weitere Befehle hinzuzufügen?

![Iobroker](https://user-images.githubusercontent.com/70971088/92773705-1f5fab80-f39d-11ea-9374-114eb3d81480.JPG)
![Fehler](https://user-images.githubusercontent.com/70971088/92773724-22f33280-f39d-11ea-916e-3ac0f71f4872.JPG)

**Comment by Gre4tOne** [comment]
Gibt es die Chance auf eine Lösung?

**Comment by Apollon77** [comment]
Also doe Fehler dort rhren von irgendeiner deiner erweiterungen her? Was hast Du denn so in deinem Browser? Mal Chrome versucht?

**Comment by Waldi544** [comment]
Ich habe Firefox, Chrome, Mircosoft Edge und auch den Samsung Browser über das Tablet probiert überall das selbe Ergebnis.
Chrome und Edge sind ohne Erweiterungen da ich die beiden eingentlich nie verwende.

**Comment by Gre4tOne** [comment]
Ich habe ebenfalls alle Browser versucht (inkl Smartphone) bei mir das gleiche (wobei ich als BS MacOS bzw. iOS habe)

**Comment by Apollon77** [comment]
Dann bitte Browser Konsole ... oben die Fehler sind alle von irgendwelchen Mozilla extensions ... ohne konkrete meldung schwer nachzuvollziehen

**Comment by Gre4tOne** [comment]
jquery.fancytree-all.js:113 Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead.
v @ jquery.fancytree-all.js:113
warn @ jquery.fancytree-all.js:3019
e.ui.fancytree._FancytreeClass.filterNodes @ jquery.fancytree-all.js:7944
(anonymous) @ adminAdapters.js:558
setTimeout (async)
(anonymous) @ adminAdapters.js:544
dispatch @ jquery-3.2.1.min.js:3
m.handle @ jquery-3.2.1.min.js:3
trigger @ jquery-3.2.1.min.js:4
(anonymous) @ jquery-3.2.1.min.js:4
each @ jquery-3.2.1.min.js:2
each @ jquery-3.2.1.min.js:2
trigger @ jquery-3.2.1.min.js:4
i @ adminAdapters.js:252
Adapters.prepare @ adminAdapters.js:573
(anonymous) @ admin.js:2000
setTimeout (async)
(anonymous) @ admin.js:1864
r.onack @ index.js:83
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83
DevTools failed to load SourceMap: Could not load content for http://192.168.178.20:8081/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.js:17 iobroker.text2command@2.0.5 using theme "colored"
instrument.ts:129 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

instrument.ts:129 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
instrument.ts:129 Help us to create open source project with reactJS!
instrument.ts:129 See you :)
instrument.ts:129 {rules: Array(18), sayitInstance: "", language: "", processorId: "", processorTimeout: 1000, …}
instrument.ts:129 {currentRules: Array(0), isOpen: false, isEdit: false, selectedRule: null, unsavedRules: {…}, …}
instrument.ts:129 {currentRules: Array(0), isOpen: false, isEdit: false, selectedRule: null, unsavedRules: {…}, …}
Layout.js:338 Uncaught (in promise) TypeError: Cannot read property 'ack' of undefined
    at Layout.js:338
    at Array.map (<anonymous>)
    at Layout.js:331
(anonymous) @ Layout.js:338
(anonymous) @ Layout.js:331
Promise.then (async)
value @ Layout.js:66
is @ react-dom.production.min.js:212
pl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ho @ react-dom.production.min.js:122
fl @ react-dom.production.min.js:248
Zs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ho @ react-dom.production.min.js:122
Ko @ react-dom.production.min.js:123
qo @ react-dom.production.min.js:122
Gs @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(anonymous) @ App.js:53
Promise.then (async)
value @ App.js:51
(anonymous) @ GenericApp.js:136
fi @ react-dom.production.min.js:131
is @ react-dom.production.min.js:212
pl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ho @ react-dom.production.min.js:122
fl @ react-dom.production.min.js:248
Zs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ho @ react-dom.production.min.js:122
Ko @ react-dom.production.min.js:123
qo @ react-dom.production.min.js:122
Gs @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(anonymous) @ GenericApp.js:136
Promise.then (async)
onReady @ GenericApp.js:127
(anonymous) @ Connection.js:283
r.onack @ socket.io.js:8
r.onpacket @ socket.io.js:8
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.ondecoded @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
a.add @ socket.io.js:6
r.ondata @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
(anonymous) @ socket.io.js:7
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
r.onData @ socket.io.js:7
ws.onmessage @ socket.io.js:8
instrument.ts:129 {currentRules: Array(0), isOpen: false, isEdit: false, selectedRule: null, unsavedRules: {…}, …}
instrument.ts:129 {currentRules: Array(0), isOpen: false, isEdit: false, selectedRule: null, unsavedRules: {…}, …}

**Comment by Waldi544** [comment]
![Iobroker_Chrome](https://user-images.githubusercontent.com/70971088/96034762-50327500-0e62-11eb-8811-836debb91bd7.JPG)

Ich habe die Fehler Konsole von Chrome probiert vielleicht kann man damit was anfangen

**Comment by Gre4tOne** [comment]
auf v 2.0.2 downgegraded jetzt wieder ein Interface ABER das hat nichts mit dem zu tun hat was ich davor kannte???
https://scontent.fvie4-1.fna.fbcdn.net/v/t1.0-9/122120762_10218206092685212_3644112813567324874_n.jpg?_nc_cat=110&ccb=2&_nc_sid=dbeb18&_nc_ohc=Tymw_cv5z4AAX9J0iaK&_nc_ht=scontent.fvie4-1.fna&oh=b0606a4e6e1d0a6f4578c9e1ebb8ce43&oe=5FB808A1

**Comment by czebulski** [comment]
Ich habe das selbe Problem, egal welcher Browser.
Hier die Konsole von Firefox:


Error while loading 'jar:file:///C:/Program%20Files/Mozilla%20Firefox/browser/omni.ja!/chrome/browser/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:600
1603579726663	addons.xpi	WARN	Exception running bootstrap method startup on twitter@search.mozilla.org: Error: Error while loading 'jar:file:///C:/Program%20Files/Mozilla%20Firefox/browser/omni.ja!/chrome/browser/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:600:20) JS Stack trace: readJSON/</<@Extension.jsm:600:20
onStopRequest@NetUtil.jsm:128:18
Unknown category for SetEventRecordingEnabled: fxmonitor
a11y.sitezoom - Unknown scalar.
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml
1603579756681	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe activity-stream-pocket-new-tab-india-new-tab-recs-study because PreferenceExperimentAction was disabled during preExecution.
1603579756713	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Comcast Steering Experiment because PreferenceExperimentAction was disabled during preExecution.
1603579756722	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe TopSites Redirect Launch US v5 because PreferenceExperimentAction was disabled during preExecution.
1603579756730	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe TopSites url Redirect Germany Launch because PreferenceExperimentAction was disabled during preExecution.
1603579756738	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe TopSites url Redirect UK Launch v5 because PreferenceExperimentAction was disabled during preExecution.
1603579756747	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe activity-stream-pocket-new-tab-story-spocs-in-uk-experiment because PreferenceExperimentAction was disabled during preExecution.
1603579756755	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Search North Star Metric Observation V2 because PreferenceExperimentAction was disabled during preExecution.
1603579756773	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Shirley Omnibus experiment because PreferenceExperimentAction was disabled during preExecution.
1603579756782	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe activity-stream-pocket-new-tab-en-global-feed because PreferenceExperimentAction was disabled during preExecution.
1603579756823	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Ongoing Fission Nightly experiment because PreferenceExperimentAction was disabled during preExecution.
1603579756833	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe ETP4 retention study because PreferenceExperimentAction was disabled during preExecution.
1603579756849	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Verify changing location service providers still gives accurate results. V2 because PreferenceExperimentAction was disabled during preExecution.
1603579756858	app.normandy.action.BranchedAddonStudyAction	WARN	Skipping recipe Third-party DNS resolver usage study V2 because BranchedAddonStudyAction was disabled during preExecution.
1603579757010	app.normandy.action.BranchedAddonStudyAction	WARN	Skipping recipe DoH US Engagement Study V2 - Add-on helper because BranchedAddonStudyAction was disabled during preExecution.
1603579757019	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Impact of Level 2 ETP on a Custom Distribution because PreferenceExperimentAction was disabled during preExecution.
1603579757090	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe WebRender Continued: v2 (Nightly Only) because PreferenceExperimentAction was disabled during preExecution.
1603579757098	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe [cmuresan][pi-507] Do No Harm Experiment for about welcome - TEST because PreferenceExperimentAction was disabled during preExecution.
1603579757109	app.normandy.action.PreferenceExperimentAction	WARN	Skipping recipe Feature Impact study for Enhanced Tracking Protection Level 2 V2 because PreferenceExperimentAction was disabled during preExecution.
